services:
  app:
    image: yiisoftware/yii2-php:8.3-apache
    container_name: yii2-app
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./app:/var/www/html:delegated
    ports:
      - "8888:80"
    working_dir: /var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: yii2-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii2_test
      MYSQL_USER: yii2_user
      MYSQL_PASSWORD: yii2_password
    ports:
      - "3306:3306"

volumes:
  mysql_data: